### ISSUE TITLE
Allow Tabs instead of Spaces

### ISSUE THREAD

**Issue by rmehner** [standardrb/standard#571]
Hey there,

big fan of Standard, been using it since first release. Thanks for all your work! 🎉 

This is somewhat a continuation of #158: In our projects we've switched to tabs wherever possible, since this is easier for our contributors with accessibility needs.

I've tried to configure Standard via the excellent `extends_config` like this:

`.standard.yml`
```yml
extend_config:
  - .tabs.yml
```

`.tabs.yml`
```yml
Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: tabs
```

but running this via `bundle exec standardrb --fix` won't yield any changes. After some reading of both documentation and the excellent code (kudos, it's really easy to follow), it's pretty clear why that is: Once a cop is set, you don't want to allow to overwrite this. This is the whole point of standard after all.

I get it and I dig it and I'm not asking you to change this behaviour at all, or even the default (people love their space and I'm not here to take it away from them 👾 ). I also know that you can go the rubocop way and include the configs of standardrb, but it's not only a discouraged way according to your README, but also a goes away from just using standard which I want to avoid.

What I'm wondering though if it would be a worthwhile exception to let people overwrite **that** one setting and document it that way. E.g. a little change to https://github.com/standardrb/standard/blob/172218fb73ba116a957e17f7a52362efb40a2e09/lib/standard/plugin/merges_plugins_into_rubocop_config.rb#L110 to permit merging for the key `Layout/IndentationStyle` or something else. 

Happy to provide a PR for this, but wanted to get in touch first to see how you feel about it.

Similar discussion happened in prettier space and there's some good arguments in there as well https://github.com/prettier/prettier/issues/7475, especially this comment from an actual affected person: https://github.com/prettier/prettier/issues/7475#issuecomment-668544890

Thanks for reading this and have a great day!

**Comment by camilopayan** [comment]
Thanks for suggestion! Unfortunately, as you pointed out, the point of StandardRb is that it can't be changed. The main way to accomplish this would be to do it in Rubocop.

Some other ideas that came to mind, though, would be seeing if the editor can display a tab instead of two spaces (which is constitutes the most common indentation method in any Ruby project) or even using [lint_roller](https://github.com/standardrb/lint_roller) in Rubocop when/if Rubocop ships `lint_roller` support to bring Standard into your configuration.
