### ISSUE TITLE
Upgrade to RuboCop 1.57.2 which drops base64

### ISSUE THREAD

**Issue by bb** [standardrb/standard#588]
Please upgrade standard to RuboCop 1.57.2. This version dropped the dependency on the base64 gem.

Earlier versions of RuboCop required base64 version 0.1.x which already caused issues before: https://github.com/rubocop/rubocop/issues/12310

A few hours ago, [v0.2.0 was released](https://github.com/ruby/base64/releases/tag/v0.2.0) and automatically loaded with new installations, thus breaking (old) RuboCop again: 

     The application encountered the following error: You have already activated base64 0.2.0, but your Gemfile requires base64 0.1.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

**Comment by camilopayan** [comment]
Thanks for the notice! It's up to date in the latest version of standard

**Comment by bb** [comment]
Great, Camilo!  🚀  Thanks for the very quick response. I tested the new release and confirmed fixes the issue. Thank you!
