### ISSUE TITLE
Add Helix to "Editor support" section in README

### ISSUE THREAD

**Issue by djpowers** [standardrb/standard#595]
Per the suggestion in the README, I'm opening an issue to request adding integration instructions for the [Helix editor](https://helix-editor.com/).

The config can essentially copy the linked exampled, or just link directly to the section on their "External formatter configuration" wiki page: https://github.com/helix-editor/helix/wiki/External-formatter-configuration#standardrb

Happy to open up a PR doing either option above if it helps.

Thanks!

**Comment by camilopayan** [comment]
Yea! I think that would be a great addition, just tag me when you add the PR.
