### ISSUE TITLE
Ruby 3.3 support

### ISSUE THREAD

**Issue by TastyPi** [standardrb/standard#603]
Ruby 3.3 introduced an issue that causes `Naming/BlockForwarding` and `Style/ArgumentsForwarding` to break https://github.com/rubocop/rubocop/issues/12571. That issue has been fixed in RuboCop `1.60`, but this gem is pinned to `1.59`.

I believe all that's needed to support Ruby 3.3 is to set `spec.add_dependency "rubocop", "~> 1.60.0"`.

**Comment by searls** [comment]
Looking now it looks like standard's current release is pegged to 1.61 so this should be resolved
