### ISSUE TITLE
add standard formatting using standardrb gem

### ISSUE THREAD

**Issue by johnreitano** [standardrb/standard#604]
Four steps
- [ ] run standardrb with "safe" fixes -- no need to review (but could be instructive)
- [ ] run standardrb with "unsafe" fixes -- need to be reviewed
- [ ] run standardrb with manual fixes  -- need to be reviewed

**Comment by searls** [comment]
Did you mean to post this on your project's repo?

**Comment by johnreitano** [comment]
woops...wrong repo...closing now. sorry about that.
