### ISSUE TITLE
`Rails/DynamicFindBy` too aggressive for JSONB queries

### ISSUE THREAD

**Issue by krystof-k** [standardrb/standard#628]
I just bumped into [`Rails/DynamicFindBy`](https://rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Rails/DynamicFindBy) rule when creating a DRY method to query records via a nested JSONB value:

```ruby
class Dummy
  def self.find_by_stripe_id(stripe_id)
    find_by!("metadata @> ?", {stripe: {id: stripe_id}}.to_json)
  end

  def stripe_id=(stripe_id)
    # This raises `Rails/DynamicFindBy`
    raise ActiveRecord::RecordNotUnique if self.class.find_by_stripe_id(stripe_id).present?
    metadata["stripe"]["id"] = stripe_id
  end
end
```

Just to consider whether this rule should be part of the default ruleset as it is quite aggressive in such cases. Or now I'm just thinking, may it be possible to fix this in RuboCop directly?

**Comment by searls** [comment]
Agree, I think we should probably nix it. In general if a rule can _ever_ tell people to do the wrong thing in a non-absurd case, I think we should default to disabling it

**Comment by searls** [comment]
Send a PR to https://github.com/standardrb/standard-rails ?
