### ISSUE TITLE
`--fix` mangles heredoc with postfix rescue clause

### ISSUE THREAD

**Issue by bcdanieldickison** [standardrb/standard#652]
example.rb:

```ruby
foo(<<~EOF) rescue nil
  bar
EOF
```

`standardrb --fix example.rb` yields:

```ruby
begin
  foo(<<~EOF)
rescue
  nil
end
  bar
EOF
```

The correct fix would be something like:

```ruby
begin
  foo(<<~EOF)
    bar
  EOF
rescue
  nil
end
```

**Comment by searls** [comment]
There is a high likelihood that this is a bug in whatever the associated Rubocop rule is. If you run without --fix you should be able to spot the name of the rule and file it there

**Comment by bcdanieldickison** [comment]
Filed the bug with Rubocop so will close this one.
https://github.com/rubocop/rubocop/issues/13291
