### ISSUE TITLE
Suggestion to adjust neovim Wiki

### ISSUE THREAD

**Issue by ryabrody** [standardrb/standard#661]
I would suggest to also include the info on how to use standard with nvim-lspconfig: https://shopify.github.io/ruby-lsp/editors.html#nvim-lspconfig in the IDE neovim Wiki: https://github.com/standardrb/standard/wiki/IDE:-neovim.

**Comment by searls** [comment]
Sounds good. Feel free to provide the markdown and we'll paste it in

**Comment by searls** [comment]
Ok. Pasted the update in hopefully helps someone
