### ISSUE TITLE
Typo `emabled` in recent release for Style/SafeNavigationChainLength

### ISSUE THREAD

**Issue by jeffbax** [standardrb/standard#662]
```
Style/SafeNavigationChainLength:
  Emabled: false
```

should be `enabled`

**Comment by searls** [comment]
lol whoops. Please send a PR!

**Comment by jeffbax** [comment]
rushing off to a hockey game right now, but can make one later if nobody else does

**Comment by jeffbax** [comment]
nm, got one in https://github.com/standardrb/standard/pull/663 but now have to run -- can update later if needed

**Comment by ScotterC** [comment]
FYI this can show up whenever running rubocop in a project that's using standard. It's pretty confusing and took me grepping all my gem paths to find it. It'd be nice to cut a minor release for this.

```ruby
Warning: Style/SafeNavigationChainLength does not support Emabled parameter.

Supported parameters are:

  - Enabled
  - Max

Warning: Style/SafeNavigationChainLength does not support Emabled parameter.

Supported parameters are:

  - Enabled
  - Max
  ```

**Comment by softwaregravy** [comment]
I suggest re-opening. The broken version of this was released. Need to get this fix out fast.
