### ISSUE TITLE
[vscode] Ruby LSP not detecting 'standard' addon?

### ISSUE THREAD

**Issue by raybrownco** [standardrb/standard#666]
# Overview

Heya! I'm not sure if this issue belongs here or over in the Ruby LSP repo, but we'll start here and see where it takes us.

I'm following the [IDE: vscode docs](https://github.com/standardrb/standard/wiki/IDE:-vscode#using-ruby-lsp) related to using Ruby LSP alongside Standard Ruby. I've updated my VS Code settings so that Ruby LSP uses `standard` as its formatter and linter. However...it doesn't appear that Ruby LSP is detecting the `standard` Ruby LSP addon at all. 

I don't see inline diagnostics from `standard`, and the ones that I _do_ see are from Prism:

<img width="540" alt="image" src="https://github.com/user-attachments/assets/587174e9-a849-4105-96b9-ba3a2a7dc006">

For reference, here's the config related to Ruby in my `.vscode/settings.json`:

```jsonc
{
  // Enable Standard Ruby formatting for all Ruby files
  "[ruby]": {
    "editor.defaultFormatter": "Shopify.ruby-lsp"
  },

  // Configure Ruby LSP to work well with Standard Ruby
  // https://github.com/standardrb/standard/wiki/IDE:-vscode#using-ruby-lsp
  "rubyLsp.enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "formatting": true
  },
  "rubyLsp.formatter": "standard",
  "rubyLsp.linters": ["standard"]
}
```

Also for reference, here's a screenshot showing the Ruby LSP saying that it's using `standard` as the formatter, but also _not_ saying that the `standard` Ruby LSP Addon is present:

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/68643d37-ea70-4830-9d0c-b8a23677f6bf">

I expect that `standard` would be yelling at me for having improper style in the `bad` method of that screenshot, but...nothing is happening. However, running `bundle exec standardrb` works as expected and complains about the style issues:

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/e3ebcf2e-99e4-4b09-bd50-b1cd31343696">

Things I've tried:

- [x] Made sure that my user settings JSON doesn't have conflicting configuration
- [x] Updating my user settings JSON to contain the same exact configuration as suggested in the docs
- [x] Uninstalling all Ruby-related VS Code extensions other than Ruby LSP
- [x] Restarting VS Code
    
What might be causing this issue?

Here are some specs that might be useful:

- macOS 15.2
- VS Code 1.95.3
- Ruby 3.3.6
- Rails 7.2.2
- Ruby LSP 0.8.13
- Standard Ruby 1.33.0

Any insight here would be deeply appreciated! And of course, I can supply more info if needed.

**Comment by searls** [comment]
Ruby LSP initially required Standard 1.39.1 or later (but really, several other fixes have landed since, as Ruby LSP is a moving target)

**Comment by raybrownco** [comment]
That did the trick! Thanks, @searls. Hope you're well! 👋
