### ISSUE TITLE
100% CPU

### ISSUE THREAD

**Issue by mperham** [standardrb/standard#685]
```
% standardrb -V    
Standard version: 1.42.1
RuboCop version:  1.68.0 (using Parser 3.3.6.0, rubocop-ast 1.36.1, analyzing as Ruby 3.2, running on ruby 3.3.5) [arm64-darwin23]
```

There does not appear to be a debug/verbose flag so I can't see/gather any diagnostic output. This happens when running `standardrb` against Sidekiq main.

src/sidekiq (main) % standardrb

**Comment by searls** [comment]
Seems bad! Unfortunately, I don't have a computer for the next couple weeks so I can't help you debug. In lieu of a verbose logger, it might make sense to bisect versions of standard to see which introduced the issue, as the most likely cause is something in the underlying pinned rubocop version

**Comment by mperham** [comment]
I'm not sure if this question makes sense so forgive my ignorance: Is there a way to invoke rubocop directly, to bypass Standard, in order to debug more directly? Is there a way to get a backtrace upon Ctrl-C when running `standardrb`? I don't even get that right now so I'm flying blind. Any pointers to docs would be appreciated.

**Comment by searls** [comment]
Take a look at this section of the README: https://github.com/standardrb/standard

**Comment by mperham** [comment]
I realized I was able to reproduce with `rubocop .` and bisect the filesystem to find the bad file. I had a 500KB .rb file with a gigantic Hash on one long line I had been using to find another bug. It would appear Rubocop does not scale well with 1000s of errors on one long line.

**Comment by searls** [comment]
Cc/ @koic if you want to consider this edge case a performance bug in rubocop
